
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn clean compile package assembly:single -DskipTests

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/semantic-conflicts/spring-boot/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-af20dc6cc45c032573413c401f9f73aa75371744
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            